<?php
$this->headTitle('Login');
?>
<div id="content">
    <div id="content-header">
        <h3><?php echo $this->escapeHtml('Login Form'); ?></h3>
    </div>
    <div class="container-fluid">
        <div class="row-fluid">
            <?php if(!empty($this->scc)): ?>
                <div class="span10">
                    <ul>
                    <?php foreach ($this->scc as $v): ?>
                        <li><?php echo $v; ?></li>
                    <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            <?php if(!empty($this->err)): ?>
                <div class="span10">
                    <ul>
                    <?php foreach ($this->err as $v): ?>
                        <li><?php echo $v; ?></li>
                    <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            <div class="span10">
                <?php
                $form = $this->form;
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="control-group">
                    <?php echo $this->formElement($form->get('security')); ?>
                </div>
                <div class="control-group">
                    <?php echo $this->formLabel($form->get('username')); ?>
                    <div class="controls">
                        <?php echo $this->formText($form->get('username')); ?>
                    </div>
                    <?php echo $this->formElementErrors($form->get('username')); ?>
                </div>
                <div class="control-group">
                    <?php echo $this->formLabel($form->get('password')); ?>
                    <div class="controls">
                        <?php echo $this->formPassword($form->get('password')); ?>
                    </div>
                    <?php echo $this->formElementErrors($form->get('password')); ?>
                </div>
                <div class="control-group">
                    <?php echo $this->formLabel($form->get('remember')); ?>
                    <div class="controls">
                        <?php echo $this->formCheckbox($form->get('remember')); ?>
                    </div>
                </div>
                <div class="form-actions">
                    <?php echo $this->formSubmit($form->get('signin')); ?>
                </div>
                <?php echo $this->form()->closeTag($form); ?>
            </div>
        </div>
    </div>
</div>