<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'TarSignup\Module'                        => __DIR__ . '/Module.php',
    'TarSignup\Controller\SignupController' => __DIR__ . '/src/TarSignup/Controller/SignupController.php',
    'TarSignupTest\Framework\TestCase'        => __DIR__ . '/tests/TarSignup/Framework/TestCase.php',
    'TarSignupTest\SampleTest'                => __DIR__ . '/tests/TarSignup/SampleTest.php',
);
